
# https://github.com/nodejs/docker-node/blob/main/README.md#how-to-use-this-image
#

services:
    helloworld-prod-nextjs-app:
        image: node:22.9.0
        volumes:
            - ./app:/var/www/html
            # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        # expose:
        #     - 3000
        # ports:
        #     - 8080:80
        ports:
            - 8080:3000
        tty: true
        working_dir: /var/www/html
        environment:
            # https://nextjs.org/docs/messages/non-standard-node-env
            #
            - NODE_ENV=development
        command: "npm run dev"
